#!/usr/bin/env python3

import sys
import gi

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import qr_alchemy.gui as gui

def main():
    window = Gtk.Window()

    get_code_window = gui.EntryDialog(
        window,
        title="QR Entry",
        message="Please Enter a custom QR Code to display. Note that the longer the qr code the harder it is to read. It is not reccommended to go over 200 characters in your message"        
    )

    if sys.argv[1] == "stop":
        return

    get_code_window.show_all()
    get_code_window.run()

    state = get_code_window.get_state()

    if state == Gtk.ResponseType.OK:
        print(get_code_window.get_result())
        sys.exit(0)

    sys.exit(1)
main()
